risky: true
preset: laravel
enabled:
  - alpha_ordered_traits
  - concat_with_spaces
  - const_visibility_required
  - linebreak_after_opening_tag
  - logical_operators
  - no_short_echo_tag
  - no_single_line_asterisk_comment
  - no_spaces_outside_offset
  - no_useless_else
  - no_useless_sprintf
  - non_printable_character
  - phpdoc_add_missing_param_annotation
  - phpdoc_separation
  - set_type_to_cast
  - simple_to_complex_string_variable
  - simplified_if_return
  - simplified_null_return
disabled:
  - phpdoc_scalar
  - concat_without_spaces
  - elseif
  - trailing_comma_in_multiline_array
