name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      php: '8.0'

    name: Style Check

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, gd
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 2
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress ${{ matrix.flags }}

      - name: Check styles
        run: vendor/bin/phpcs
